import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    // Without this, vitest's default include glob also matches compiled
    // *.test.js under dist/ (a gitignored build artifact regenerated by
    // `npm run build`), running every test twice. For integration tests
    // that share one live Neo4j container, the src/dist duplicate runs
    // race each other's seed/cleanup and produce flaky failures.
    exclude: ['**/node_modules/**', '**/dist/**'],
  },
});
